Sistema_Contactos/Sistema_Contactos/Controllers/RegistroController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Proyecto_Bb_2.Models;
using MongoDB.Bson;
using MongoDB.Driver;

namespace Proyecto_Bb_2.Controllers
{
    public class RegistroController : Controller
    {
        private readonly IMongoCollection<Registro> _registro;
        public RegistroController(IMongoClient mongo)
        {
            var Db = mongo.GetDatabase("Proyecto_Bb_2");
            _registro = Db.GetCollection<Registro>("Contactos");
        }

        public async Task<IActionResult> Index()
        {
            var Registros = await _registro.Find(_ => true).ToListAsync();
            return View(Registros);
            
        }
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Crear([Bind("Name","Edad","Celular","Correo")] Registro registro, IFormFile foto)
        {
            registro.Id = ObjectId.GenerateNewId().ToString();
            if (foto != null && foto.Length > 0)
            {
                var subir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Subidos");
                //Cambiar nombre
                var filename = Path.GetFileName(foto.FileName);
                var filepath = Path.Combine(subir, filename);
                //Guardar imagen
                using (var stream = new FileStream(filepath, FileMode.Create))
                {
                    await foto.CopyToAsync(stream);
                }
                registro.Foto = $"/Subidos/{filename}";
            }
            else
            {
                registro.Foto = "/Defecto/Contac_img.jpg";
            }
            try
            {
                await _registro.InsertOneAsync(registro);
                Console.WriteLine($"Nuevo Contacto creado {registro.Name}");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                ModelState.AddModelError(" ","Error insertando documento");
                return View(registro);
            }
        }

        public async Task<IActionResult> Editar(string Id)
        {
            if (Id == null)
            {
                Console.WriteLine("Error al recibir el Id");
                return NotFound();
            }
            var registro = await _registro.Find(p => p.Id == Id).FirstOrDefaultAsync();
            if (registro == null)
            {
                return NotFound();
            }
            return View(registro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Editar(string Id, Registro registro, IFormFile foto)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var registro_ex = await _registro.Find(p => p.Id==Id).FirstOrDefaultAsync();
            if (registro_ex == null)
            {
                return NotFound();
            }
            ModelState.Remove("Foto");
            //si se sube una nueva foto, reemplzar la anterior
            if (foto != null && foto.Length > 0)
            {
                var subir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Subidos");
                var filename = Path.GetFileName(foto.FileName);
                var filepath = Path.Combine(subir, filename);

                using (var stream = new FileStream(filepath, FileMode.Create))
                {
                    await foto.CopyToAsync(stream);
                }
                registro.Foto = $"/Subidos/{filename}";
            }
            else
            {
                registro.Foto = registro_ex.Foto;
            }
            if (ModelState.IsValid)
            {
                await _registro.ReplaceOneAsync(p => p.Id == Id, registro);
                Console.WriteLine($"El contacto de {registro_ex.Name} se edito correctamente");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                foreach (var modelError in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(modelError.ErrorMessage);
                 }
                return View(registro);
            }
            
        }

        public async Task<IActionResult> BorrarC (string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var registro = await _registro.Find(p => p.Id==Id).FirstOrDefaultAsync();
            if (registro == null)
            {
                return NotFound();
            }
            
            return View(registro);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Borrar(string Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            await _registro.DeleteOneAsync(p => p.Id == Id);
            Console.WriteLine($"El contacto fue borrado correctamente");
            return RedirectToAction(nameof(Index));
        }
    }
}

Sistema_Contactos/Sistema_Contactos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema_Contactos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sistema_Contactos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registro" asp-action="Index">Contactos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actividades" asp-action="Index">Actividades</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Todos los derechos reservados. Juan Jose Tito - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>